---
title: "Mouseprep workflow"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{workflow}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(mousePrep)
```

```{r include=FALSE}
#rename columns to facilitate mousePrep usage 
stand_df <- standardize_colnames(df1)

#convert every possible numeric column into numeric
stand_df <- convert_numeric(stand_df, exclude = "mt_id")

#remove specific participant based on their id
part_vector <- unique(stand_df$mt_id[1:100]) #select random cases here
stand_df2 <- rm_part(stand_df, rm_vector = part_vector)

# remove cases that are not needed
stand_df3 <- stand_df2 %>%
  rm_cases(column_rm = "userAgent_is_touch_capable",
           factor_rm = TRUE,
           criteria = 1) %>%
  rm_cases(column_rm = "type",
           factor_rm = "resize",
           criteria = 1) 

#remove cases where participants needed more than 7 minutes for a question
stand_df4 <- rm_cases_time(stand_df3, time_col = "timestamps", part_id = "mouseid", max_time = 7)

# create click and time df for include_clicks()
click_df <- sl_cases(stand_df4, column_sl = "type", factor_sl = "click")
time_df <- calculate_time_vars(stand_df4)

#inspect outliers based on move_time from the calculate_time_vars function on mt_id level 
time_data <- flag_outliers(time_df, flag_outliers = "threshold", outlier_threshold = 120000)

# select all the mousemove events and save them as a df
stand_df5 <- sl_cases(stand_df4, column_sl = "type", factor_sl = "mousemove")

#remove participants with multiple visits
stand_df6 <- multiple_traj(stand_df5, part_id = "mouseid", quest_id = "screen", criteria = "all")
stand_df6 <- stand_df6[stand_df6$multiple_workers == FALSE,]

#inspect cases with less than 50 recorded mouse movement data points per screen (flagged)
touch_df <- mouse_class_col(stand_df6, max_cutoff = 50)

#keep cases with more than 50 recorded mouse movement data points per screen
mouse_df <- mouse_class(stand_df6, max_cutoff = 50)

#calculate screen dimensions
screen_dims_data <- calculate_screen_dims(mouse_df)

#include clicks in an extra column 
click_df <- data.frame(mt_id = click_df$mt_id, timestamps = click_df$timestamps)
df_merged <- left_join(mouse_df, time_df, by = "mt_id")

df_with_clicks <- include_clicks(data_complete = df_merged, data_clicks = click_df)
df_with_clicks <- df_with_clicks %>% select(-clicks_char)

#export data
long_data <- mp_export_data(data = mouse_df, direction = "long")
processed_data <- mt_process_data(data = mouse_df,nsteps = 101,hover_threshold = 500)

```

